// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package models

// Address defines model for Address.
type Address = string

// AddressFilter defines model for AddressFilter.
type AddressFilter = Address

// Age defines model for Age.
type Age = int64

// Count defines model for Count.
type Count struct {
	Total int64 `json:"total"`
}

// Dag defines model for Dag.
type Dag struct {
	Age              Age   `json:"age"`
	Hash             Hash  `json:"hash"`
	Level            int64 `json:"level"`
	TransactionCount int64 `json:"transactionCount"`
}

// Hash defines model for Hash.
type Hash = string

// Pbft defines model for Pbft.
type Pbft struct {
	Age              Age   `json:"age"`
	Hash             Hash  `json:"hash"`
	Number           int64 `json:"number"`
	TransactionCount int64 `json:"transactionCount"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	Age      Age     `json:"age"`
	Block    int64   `json:"block"`
	From     Address `json:"from"`
	GasPrice string  `json:"gasPrice"`
	GasUsed  string  `json:"gasUsed"`
	Hash     Hash    `json:"hash"`
	Index    int64   `json:"index"`
	Status   bool    `json:"status"`
	To       Address `json:"to"`
	Value    string  `json:"value"`
}

// Validator defines model for Validator.
type Validator struct {
	Address   Address `json:"address"`
	PbftCount int64   `json:"pbftCount"`
}

// WeekFilter defines model for WeekFilter.
type WeekFilter struct {
	Week int32 `json:"week"`
	Year int32 `json:"year"`
}

// GetValidatorsParams defines parameters for GetValidators.
type GetValidatorsParams struct {
	// Filter Week to filter by
	Filter WeekFilter `form:"filter" json:"filter"`
}

// GetValidatorsTotalPbftBlocksParams defines parameters for GetValidatorsTotalPbftBlocks.
type GetValidatorsTotalPbftBlocksParams struct {
	// Filter Week to filter by
	Filter WeekFilter `form:"filter" json:"filter"`
}
